spring:
  application:
    name: lv3-final-mission
  datasource:
    url: jdbc:mysql://danny-dev.cqsc6pyqhwww.ap-northeast-2.rds.amazonaws.com:3306/danny-dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false

jwt:
  secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  token:
    expiration-time: 3600000

rest-client:
  connection-timeout: 5000
  read-timeout: 35000

randommer-secret-key: 89627a4a47fb446c881d2b346ba7f588
