spring:
  application:
    name: lv3-final-mission
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false

jwt:
  secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  token:
    expiration-time: 3600000

rest-client:
  connection-timeout: 5000
  read-timeout: 35000

randommer-secret-key: 89627a4a47fb446c881d2b346ba7f588

management:
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    export:
      cloudwatch:
        namespace: "DannyLocal"
        step: "1m"
